[package]
name = "night-light-dialog"
version = "0.1.0"
edition = "2024"

[dependencies]
gio = "0.21.0"
glib = "0.21.0"
gtk4 = { version = "0.10.0", features = ["v4_18"] }
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.2"
which = "8.0.0"
