presets = [
  { label = "2K",   value = 2000 },
  { label = "2.5K", value = 2500 },
  { label = "3K",   value = 3000 },
  { label = "3.5K", value = 3500 },
  { label = "4K",   value = 4000 },
  { label = "4.5K", value = 4500 },
  { label = "5K",   value = 5000 },
  { label = "5.5K", value = 5500 },
  { label = "6K",   value = 6000 },
  { label = "6.5K", value = 6500 }
]
